### ISSUE TITLE
Submit button not working when given locations in two different countries. Should give a information dialog box.

### ISSUE THREAD

**Issue by PulkitMathur** [airavata-courses/Envy#100]

**Comment by thumblas** [comment]
Hi @PulkitMathur ,

The public Api we are using for the flights  search is for the cities in US. Therefore it won't work if you provide different countries.

Thanks,
Shivani

**Comment by alakhsingh** [comment]
Hi @PulkitMathur ,
Yes, we will add an alert if any other country's address is given.
Thanks,
Alakh
