### ISSUE TITLE
Peer Review Summary - Milestone #3

### ISSUE THREAD

**Issue by PulkitMathur** [airavata-courses/Envy#101]
Hello,

I started reviewing your application. Following are my observations:

1. Idea is very impressive.

2. Well structured and clearly defined Wiki page.

3. Feature Improvement points: 
- Origin and destination address drop down can be provided so that user doesn't need to type in complete location.

4. Error loading page when refreshed page results (https://github.com/airavata-courses/Envy/issues/99)

5. No way to close the travel guide once clicked on it.

6. Submit button not working (https://github.com/airavata-courses/Envy/issues/100).

**Comment by alakhsingh** [comment]
Hi Pulkit,
Thank you for the suggestions, 
We will work on it by the next milestone.

Thanks,
Alakh
