### ISSUE TITLE
Peer Review Milestone 3

### ISSUE THREAD

**Issue by chetan253** [airavata-courses/Envy#103]
Hi Team,

I need access to your Jenkins and Kubernetes master instance. Kindly send me the .pem and jenkins credentials on cpatil@iu.edu

Chetan

**Comment by chetan253** [comment]
Hi Team,

I've reviewed the system based on Milestone 3 and made following observations: 

- Wiki properly describes the system flow and is well documented
- Jmeter results are as expected and displayed on wiki
- Auto deployment via Jenkins to Kubernetes is working properly
- Kubernetes cluster is well setup and taking down instances doesn't affect availability and services are auto-deplyed with proper load balancing

Some issues I faced are: 
- It takes a bit long time when we request for cab/cars i.e on search page
- Sometimes on submit request there is the following error: 
![image](https://user-images.githubusercontent.com/11805422/55526421-0a88cf80-5663-11e9-8444-4a9655d58364.png)

- Sometimes after submit there are no results
![image](https://user-images.githubusercontent.com/11805422/55526700-01e4c900-5664-11e9-978d-1d96c392999e.png)

- After pressing back the search page is disappeared and/or not found:
![image](https://user-images.githubusercontent.com/11805422/55526706-07421380-5664-11e9-8b10-ee340086a73c.png)

Some small tweaks in code might fix above bugs. Based on overall architecture, the system seems to be great!! 

Some suggestions:
As your system is heavily dependent on APIs, I would suggest caching the data based on 2 locations and get new data based on time or any other suitable factor. This will be much faster with less response time to end user and your api hit limit will be less as well.

Best,
Chetan

**Comment by alakhsingh** [comment]
Hi @chetan253 ,
Thanks for letting us know.
The above issues you get are because we have not done session management yet. We will do that in the upcoming milestone. 
The blank result screen was because we introduced a new micro service yesterday to compensate for the loss of our public API which stopped working during load testing. The new service we feel has a few bugs and we will be fixing this in future sprints as well.

Thanks,
Alakh

**Comment by chetan253** [comment]
Perfect!! I'm closing this issue.

-Chetan
