### ISSUE TITLE
Documentation changes for Milestone 3

### ISSUE THREAD

**Issue by thumblas** [airavata-courses/Envy#104]

**Comment by thumblas** [comment]
[(https://github.com/airavata-courses/Envy/wiki/Assignment-3/6aad4dae8a515a551012b12a2ee708c6c7520d9d)]

https://github.com/airavata-courses/Envy/wiki/Assignment-3/8b7bc070efca849c3e04d14292ab2a362547e5e1]

**Comment by thumblas** [comment]
[link:]((https://github.com/airavata-courses/Envy/wiki/Assignment-3/6aad4dae8a515a551012b12a2ee708c6c7520d9d)l)

https://github.com/airavata-courses/Envy/wiki/Assignment-3/8b7bc070efca849c3e04d14292ab2a362547e5e1]

**Comment by thumblas** [comment]
[https://github.com/airavata-courses/Envy/wiki/Assignment-3/6aad4dae8a515a551012b12a2ee708c6c7520d9d](url)

**Comment by thumblas** [comment]
[https://github.com/airavata-courses/Envy/wiki/Assignment-3/8b7bc070efca849c3e04d14292ab2a362547e5e1](url)

**Comment by alakhsingh** [comment]
https://github.com/airavata-courses/Envy/wiki/Assignment-3/6aad4dae8a515a551012b12a2ee708c6c7520d9d

**Comment by alakhsingh** [comment]
https://github.com/airavata-courses/Envy/wiki/Assignment-3/efeebf1ede4ec3f674800473a642f7531d246104
