### ISSUE TITLE
PR4: UI- Unknown error message popup

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/Envy#108]
![image](https://user-images.githubusercontent.com/43358590/56708219-e52f3480-66e9-11e9-83bb-af834139c521.png)
Unknown error message popup

**Comment by alakhsingh** [comment]
Hi,
Thank you for pointing out the bug. We are fixing it and will get back to you.

Thanks,
Alakh

**Comment by alakhsingh** [comment]
Also, I hope the address autocomplete is working as the previous users had a hard time figuring out the input format. 
Thanks,
Alakh

**Comment by alakhsingh** [comment]
I have added a fix for this bug. Can you check and close?
Thanks

**Comment by harishmaruthi** [comment]
Works like a champ!!
But, If one of the address isn't incorrect. User can't figure out the erroneous input.

And yes, the autocomplete of address works fine.

Closing the issue.
