### ISSUE TITLE
PR4: UI- Error Message to handle invalid date input

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/Envy#109]
Please note "Select another date" isn't specific. If app doesn't allow past date selection it would be user friendly to either disable Past dates being displayed. Or, May be a message "Select date in future".

![image](https://user-images.githubusercontent.com/43358590/56709387-0181a000-66ef-11e9-81ef-11a3fba1d596.png)

**Comment by alakhsingh** [comment]
Hi,
Yes of course. We added the validation internally but we should also display proper error messages which are understandable. We also thought the user might want to book tickets for the future. Will update it.
Thanks,
Alakh

**Comment by harishmaruthi** [comment]
Thanks for considering the suggestion team. We have done a great job. UI is beauty. Looks good.

**Comment by alakhsingh** [comment]
I have pushed the bug fixes. Can you check and close?
Thanks
