### ISSUE TITLE
PR4: Search is not returning any result. No response

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/Envy#110]
After selecting a valid date. Clicking on search is not showing any results.

**Comment by alakhsingh** [comment]
Hi,
Can you please try again and please select locations which are in different cities for better results.
If that doesn't work, please let us know the search criteria which might be a bug.

Thanks,
Alakh

**Comment by harishmaruthi** [comment]
![image](https://user-images.githubusercontent.com/43358590/56709764-05aebd00-66f1-11e9-8aa3-bbfea0a96378.png)

**Comment by harishmaruthi** [comment]
works fine

![image](https://user-images.githubusercontent.com/43358590/56709825-50c8d000-66f1-11e9-83ca-4f34edcb840c.png)
