### ISSUE TITLE
PR4: UI- Field values needs to be wrapped to avoid overflow  

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/Envy#111]
![image](https://user-images.githubusercontent.com/43358590/56709902-ad2bef80-66f1-11e9-9b57-bec54d4ed258.png)

"Alaska Airlines 494.57000000000005$"

It may happen that the value flow out of the display card. Also, value can be rounded.

**Comment by alakhsingh** [comment]
HI,
haha, I hadn't noticed. This is good. We will fix it and let you know.

Thanks,
Alakh

**Comment by alakhsingh** [comment]
Hi,
fixed it. Commit hash  6c07579e1636fc872db1169ace4cf766b86f4443

Thanks,
Alakh

**Comment by harishmaruthi** [comment]
Team,

Well Done. Good turnaround. 

Closing this issue.

-Harish
