### ISSUE TITLE
PR4: Please share Blue Green deployment details.

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/Envy#112]
Hello Team,

Please let me know how and where I can test Blue Green deployment.
(Update wiki)
Thanks,

Harish.

**Comment by alakhsingh** [comment]
We have updated the wiki.

**Comment by harishmaruthi** [comment]
Thank you. I am looking into the implementation.

I will start a new thread if there are any concerns/feedback.

-Harish.
