### ISSUE TITLE
Main site login / signup bug

### ISSUE THREAD

**Issue by tylerthedeveloper** [airavata-courses/Envy#116]
cannot stay on the site without it crashing

![Screen Shot 2019-04-26 at 1 53 59 PM](https://user-images.githubusercontent.com/13102536/56826686-d9975700-682a-11e9-99ea-63baa7820351.png)

**Comment by alakhsingh** [comment]
Hi Tyler,
Looks like our db is down which is why you are seeing this error.
Can you try again and check?
Thanks

**Comment by alakhsingh** [comment]
Hi,
Please use the domain name specified i.e. http://js-171-47.jetstream-cloud.org/ to access our website. 
The reason it won't work with IP address is that google OAuth needs a domain name to work.
Thanks,
Alakh
