### ISSUE TITLE
Peer Review: Milestone 4

### ISSUE THREAD

**Issue by aralshi** [airavata-courses/Envy#117]
Front end issue:
![Screen Shot 2019-04-26 at 4 26 03 PM](https://user-images.githubusercontent.com/32557745/56834943-ddce6f00-6840-11e9-8484-afb41ac57c91.png)

**Comment by alakhsingh** [comment]
Hi,
Please use the domain name specified i.e. http://js-171-47.jetstream-cloud.org/ to access our website. 
The reason it won't work with IP address is that google OAuth needs a domain name to work.
Thanks,
Alakh

**Comment by aralshi** [comment]
Hi Team,

UI looks good. I was able to use google to login to the application. However search form can be improved to help user understand what needs to be entered. It is difficult to understand the date field and the uber option. Also Search does not always return results.

Issues:
1. Search is not returning any results for some test cases
2. Sign in page should not have button to logout. (I encountered that once while testing)
![Screen Shot 2019-04-26 at 6 24 52 PM](https://user-images.githubusercontent.com/32557745/56839469-a23ba100-6850-11e9-86ca-dad75d330411.png)

Suggestion:

1. On Search form, there should be some label for date field to understand what is expected to be entered. Also you guys can make it date field rather that asking user to enter a data manually or mention the format.
2. You can allow functionality to save results for previous search for a user.

Overall great job!!

Thanks,
Ankita Alshi

**Comment by alakhsingh** [comment]
Hi,
Thank you for reviewing. Yeah, there are a few limits we have set so that our only source of flight information is not stopped.
That was a good find about the logout button. We will fix it right away. 
Will consider your suggestions.
Thanks,
Alakh
