### ISSUE TITLE
PR4- Blue Greed Deployment feedback.

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/Envy#118]
Hello Team,

The process of Blue Green deployment setup has taken a lot of time and effort to implement. Although the essence of Blue Green deployment as suggested in the video, 
https://dzone.com/articles/how-to-implement-continuous-delivery-for-nodejs-us , is to automate the production release maintenance. Maintaining version control branches separately is a overhead of documenting release details for blue/green branches. Multiple working branches for development for development across the organization, and switching will not be easy especially in case of daily releases!
Overall it is a great effort and good job by the team.

Thanks,

Harish.

**Comment by alakhsingh** [comment]
Hi Harish,
Thank you for reviewing. Yes, we can change from blue to green if there is an issue with the release by applying the yaml file. but what you say is correct.

Thanks,
Alakh
