### ISSUE TITLE
[Wiki] improve DB deployment steps

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Envy#36]
1. Since this is the first step in your wiki, you should include git clone and git checkout command.
2. You are asking to run the file using \i command, that is enough, no need to redirect the user to that file.
3. Also add the link to postgres home page.
4. what is 'postgres command line' and how to fire it up?

After updating the wiki, please **include the commit id** here, then I will mark below checkboxes after verification and close the issue.
- [x] Add git clone and checkout commands.
- [x] Remove redirect to 'DB creation and initialization', ask user to directly run the file.
- [x] Add link to download postgres DB.
- [x] Write steps to navigate user to postgres installation directory/bin folder and find psql binary

**Comment by alakhsingh** [comment]
0e3ef5e Added git clone commands on the top

**Comment by KalaRaja** [comment]
verified and closing the issue, the check boxes in the issue is for me, i would have verified and marked them one by one , anyway good job. Please include the commit ids from next time.
