### ISSUE TITLE
[POSTGRES DB] DB credentials

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Envy#37]
![image](https://user-images.githubusercontent.com/42894144/52511195-eeb9fd80-2bcc-11e9-9b2e-f3e3043551f3.png)

Explain the steps to get psql shell connected to 'postgres' db.

Attach your commit id here.

- [x] Added steps for psql shell to connect to 'postgres' DB.

**Comment by alakhsingh** [comment]
Hi,
There is an issue with db connection and permissions for tables which will not allow you to login or use any other services in the application. Will update you after resolving those and updating the wiki.

**Comment by KalaRaja** [comment]
@alakhsingh that's okay, I am just trying deployment.
