### ISSUE TITLE
[Login-Signup backend service setup] git clone not working

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Envy#38]
Git clone to **Login-Signup backend service setup** not working, I copy pasted the command from Wiki

![image](https://user-images.githubusercontent.com/42894144/52511896-24acb100-2bd0-11e9-9103-cd1b290d5b58.png)

add your commit id here.

- [x] git clone to this repo is now  working.

**Comment by alakhsingh** [comment]
@KalaRaja I tried it in some other laptop and it worked fine. It looks like it is related to your public key. Try adding the key and clone again.

**Comment by KalaRaja** [comment]
since you updated the wiki, i'm closing the issue.
