### ISSUE TITLE
[Login-Signup backend service setup] npm install and npm start errors

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Envy#40]
git cloned and git checkout to the right branch, then ran npm install and npm start, got the following errors

![image](https://user-images.githubusercontent.com/42894144/52512339-545cb880-2bd2-11e9-80d9-b7772204cc5e.png)

**EDIT : looks like you forgot to add cd ./travel in your wiki.**
Add your commit id here

- [x] Fixed npm install errors.
- [x] Fixed npm start errors.
- [x] Service is up and running.

**Comment by alakhsingh** [comment]
@KalaRaja Wiki did not specify the file directory you need to go in the last commit. Have updated the wiki for the same.
