### ISSUE TITLE
[Database Setup] insert.sql throws airport_index relation does not exist.

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Envy#44]
i used the database setup wiki to setup the DB, please see below errors.

![image](https://user-images.githubusercontent.com/42894144/52522000-c4f4eb00-2c4d-11e9-9a28-7bae31d13e2c.png)

- [ ] Make sure to drop database at the start of the sql script so that there are no conflicts.
- [ ] Scripts run successfully from the scratch.

**Comment by alakhsingh** [comment]
Hi,
I am not sure why airport_index doesn’t exist. Did you first try initializer.sql before running insert.sql? Also, you should use insert.sql from “api” database.

**Comment by KalaRaja** [comment]
@alakhsingh i ran the initializer sql file, I wanted to do everything from scratch again i got some errors, Please see #45
