### ISSUE TITLE
[Database Setup] cannot re-run sql files.

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Envy#45]
When i try to run the initializer / insert sql files, there are erros like database api already exists.
When i try to manually drop the roles and databases, it fails giving me an error - 10 other sessions are using the database.

EDIT : i had shutdown all other services, still giving me error 10 sessions are using this database, cannot drop it.

![image](https://user-images.githubusercontent.com/42894144/52522548-d7beee00-2c54-11e9-9bc3-7f06fb3a507d.png)

![image](https://user-images.githubusercontent.com/42894144/52522557-ed341800-2c54-11e9-91a1-29d46ca97c01.png)

- [ ] Modify the scripts so that user can reset the databases by running the scripts again.
- [ ] Write instructions to close other sessions vefore dropping the databases/roles.

**Comment by varun-mach** [comment]
Could you check in your control panel if any java or node session is running. If there is, end those process and please try again.

**Comment by KalaRaja** [comment]
@varun-mach Alakh will fix the sql files later today, then i will try this method.
