### ISSUE TITLE
Python Module and version error

### ISSUE THREAD

**Issue by shubham1812** [airavata-courses/Envy#46]
While starting python server, getting rest_framework module not found error
![1](https://user-images.githubusercontent.com/5382862/52524589-8ae71180-2c6c-11e9-9bb8-34e37e7ad163.png)

Did pip install djangorestframework and got this error
![3](https://user-images.githubusercontent.com/5382862/52524608-c8e43580-2c6c-11e9-98d1-a9d1a3a36ff6.png)

Instead of pip install virtualenv Do pip install psycopg2 to solve that and got this error:
![4](https://user-images.githubusercontent.com/5382862/52524638-1d87b080-2c6d-11e9-8462-ba6f7dd17068.png)

Probably some issue with python version. Please mention which python version to use.

Suggestion:
Create a requirement file in python api folder and mention all the requirements there
So, the user only has to do pip install -r requirements.txt

**Comment by alakhsingh** [comment]
Hi @shubham1812 You are supposed to run this service using python 2.7 as it was not mentioned in the wiki earlier. I have modified the wiki cd5d77f

**Comment by alakhsingh** [comment]
Hi @shubham1812 , I have created the requirements.txt file you have suggested 2d6af550c4b58313bf9e1868e832ae9036bca269
