### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Envy#53]
Hey team,

I just started with the code review. Will update my progress/issues here.

Thanks,
Nawaz

**Comment by nawazkh** [comment]
Hey Team,

I am facing issues with cloning the repo and following up with your project.
1) Please correct your wiki for installation steps, mention that the folders needed to create folders to checkout the code and build it.
2) Please mention the steps to install Postgres in Linux flavor.

Please update this issue soon, I will continue with the review.

Thanks,
Nawaz

**Comment by alakhsingh** [comment]
Hi Nawaz, 
I have updated the wiki.
For the posgres part, I used the same link from wiki and downloaded the Linux flavor mentioned there to test this application.
<img width="842" alt="screenshot 2019-02-20 at 4 35 27 pm" src="https://user-images.githubusercontent.com/20154848/53126183-99b3ab00-352d-11e9-8a3b-d96d5503049d.png">
The above screenshot is from the link attached in the wiki. I have not included the steps to set the path variable for Linux as when I installed it in Mac OS and Ubuntu, I didn't face any issues. 
Steps I followed: download the required flavor -> Install the application
Also, please make note of the password during the installation process. 
Then follow the wiki from step 4. 

Please let me know if you have any other issues.

Thanks,
Alakh

**Comment by nawazkh** [comment]
Hey Team, 

I just completed the review, and I love this project! Its really good!

Documentation is up to the point now, with one change, that when a user clones your project in a linux environment, Postgres asks for Postgres password just before one imports all the queries. If you could mention the password to be "postgres" as the default password in the wiki, it should be helpful. 

Please also mention which micro-service is being built in which language and the purpose it serves.

Closing the ticket from my end.
Keep up the good work! 

Thanks, 
Nawaz

**Comment by alakhsingh** [comment]
Hi Nawaz, 
Will update the wiki with micro service description and the Postgres description as well.
Thanks for the kind words. Glad you liked it.

Thanks,
Alakh
