### ISSUE TITLE
Not able to sign up and login to the application

### ISSUE THREAD

**Issue by arswaroop** [airavata-courses/Envy#67]
I tried signing up. After i press the sign up button, it doesnt give any confirmation of sign up.
Nevertheless i tried to login using those credentials. It returned a popup "Invalid Credentials" with the same creds i used to sign up.

**Comment by alakhsingh** [comment]
Hi,
Can you try signing up again?
Fixed the issue. Also, we do not have any loaders in the UI. So the only confirmation is when the page state changes, which it will.
Thanks,
Alakh

**Comment by alakhsingh** [comment]
Closed the issue by mistake.

**Comment by gattur** [comment]
Hi Alakh,
Still not able to login.

Thanks,
Gattu

**Comment by arswaroop** [comment]
I am able to login to the application. Keeping issue open until Gattu is able to login

**Comment by alakhsingh** [comment]
I spoke to @gattur . He was in the search page. He was able to login.

Thanks,
Alakh
