### ISSUE TITLE
Submit button on the home page does nothing.

### ISSUE THREAD

**Issue by arswaroop** [airavata-courses/Envy#70]
![image](https://user-images.githubusercontent.com/41299771/53708515-d622b900-3e01-11e9-9126-7b4277c7cb3b.png)

**Comment by alakhsingh** [comment]
Hi,
Yes, we are having an issue with Jenkins. We are working on it right now.

Thanks,
Alakh

**Comment by alakhsingh** [comment]
@arswaroop We fixed it. Can you please check and let us know?
http://149.165.168.73:3001/ 
We changed the UI IP
Thanks,
Alakh

**Comment by arswaroop** [comment]
Yes its working now
