### ISSUE TITLE
Peer review - Milestone 2

### ISSUE THREAD

**Issue by absheth** [airavata-courses/Envy#76]
Hi Team,

Good job! 

There are a few issues with Login service not being deployed with Jenkins and option to select the cheapest flight not available. 

But apart from these issues, I like the idea that a person would be able to find the cheapest rates for multiple modes of transport in one place.

A few suggestions - Does not mean you have to implement it :) :
1) You can implement the calendar to select the date of journey.
2) I believe the UI has a lot of space which can be utilized to implement some other functionality like showing a map or suggest some places to visit based on the search.

**Comment by thumblas** [comment]
Hi Akash,

our application suggests the cheapest option after you enter the source and destination. We are not planning to add the option for cheapest flights. Its one of our micro service. 

We surely think of the  suggestions you gave regarding UI in future sprints.
