### ISSUE TITLE
Peer Review Summary - Milestone 2

### ISSUE THREAD

**Issue by arswaroop** [airavata-courses/Envy#81]
Hey Team,
following is the summary of my reviews-
- UI looks super nice.
- CI/ CD works fine. 
- Github web hooks work perfectly.
- Wiki instructions were clear and things worked as described.

Issues faced-
- Theres no validation for dates. Old dates are getting accepted and empty date gives an error (Page not found). have opened https://github.com/airavata-courses/Envy/issues/78
- Due to a lack of session management, going back and forth the website causes it to throw errors. https://github.com/airavata-courses/Envy/issues/79
- Jenkins has a single pipeline causing whole app to re-deploy even for small fixes. Better you have separate pipelines for each service. https://github.com/airavata-courses/Envy/issues/77
- Not Sure your flights API is working. https://github.com/airavata-courses/Envy/issues/80

Would love to see-
- Implementation of Google geolocation and Uber API as mentioned in Architecture diagram.
- Do more with it, like links to booking flights and uber rides

**Comment by alakhsingh** [comment]
Hi Swaroop,
Thanks a lot for reviewing after so many issues.
We have used google Geolocation and Uber API.
Yes, we will definitely consider your suggestions.
Thanks,
Alakh
