### ISSUE TITLE
MileStone 2 Peer Review

### ISSUE THREAD

**Issue by gattur** [airavata-courses/Envy#82]
Hi Team,

Great work!
1. Good support from team when facing issues, especially @alakhsingh .
2. UI looks really amazing, especially the background.
3. CI/CD works as expected.

A Suggestions, after searching for the ride, you might add an pop up or show loading so as to make the user know it has started processing the search request.

**Comment by alakhsingh** [comment]
Thanks a lot, gattu. Appreciate your feedback.
