### ISSUE TITLE
Peer Review for Milestone 3

### ISSUE THREAD

**Issue by maheshbelnekar** [airavata-courses/Envy#91]

**Comment by maheshbelnekar** [comment]
Hey Team,
 I have started reviewing the application. The documentation is very descriptive and easy to understand. For now I have come across below issues:
1. On page refresh, the webpage stops responding
2. Session management missing for UI/frontend

I will keep updating this thread as I find more issues.

**Comment by maheshbelnekar** [comment]
@alakhsingh Can you please send me your kubernetes master's ip also you email address to send you my public key.

**Comment by alakhsingh** [comment]
Kubernetes master IP: 149.165.170.230
Mail your public IP to araghuv@iu.edu

Thanks,
Alakh

**Comment by maheshbelnekar** [comment]
Thank you. I have reviewed your k8s cluster and everything seems to be working as expected.
Apart from the 2 issues mentioned above and other issue raised by peer reviewers, everything is working as expected.
Good work team!

Thanks.
